name: Build official Chia Docker Image

on:
  workflow_dispatch:
    inputs:
      upstream_branch:
        description: 'chia branch name to use'
        required: true
        default: 'dev'
      image_tag:
        description: 'special tag for this image build'
        required: true
        default: 'unstable'

jobs:
  docker_build_and_publish:
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGE_ADMIN_PAT }}

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Docker Prune
        run: docker system prune --all

      - name: Get Registration Token
        id: get_reg_token
        run: |
          sudo apt-get -y install jq
          echo "curl -X POST -H "Authorization: token ${{ secrets.ORG_ADMIN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/orgs/horego/actions/runners/registration-token | jq -r '.token'"
          echo "::set-output name=reg_token::$(curl -X POST -H "Authorization: token ${{ secrets.ORG_ADMIN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/orgs/horego/actions/runners/registration-token | jq -r '.token')"

      - name: Build docker image
        run: docker build --no-cache --build-arg BRANCH=${{ github.event.inputs.upstream_branch }} -t ghcr.io/horego/chia-docker:${{ github.event.inputs.image_tag }} .

      - name: Push to github packages
        run: docker push ghcr.io/horego/chia-docker:${{ github.event.inputs.image_tag }}
