name: Build official Chia Docker Image

on:
  workflow_dispatch:
    inputs:
      upstream_branch:
        description: 'chia branch name to use'
        required: true
        default: 'latest'
      image_tag:
        description: 'special tag for this image build'
        required: true
        default: 'unstable'

jobs:
  docker_build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Docker Prune
        run: docker system prune --all

      - name: Build docker image
        run: docker build --no-cache --build-arg BRANCH=${{ github.event.inputs.upstream_branch }} -t ghcr.io/horego/chia-docker:${{ github.event.inputs.image_tag }} .

      - name: Push to github packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: horego/chia-docker/my-image
          tag_with_ref: true
